/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_RepositorySearch_Console */

#ifndef _Included_org_RepositorySearch_Console
#define _Included_org_RepositorySearch_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_RepositorySearch_Console
 * Method:    PrintDelimiter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_RepositorySearch_Console_PrintDelimiter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
